name: chatbydatabase
description: Flutter by Realtime Database

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.2
  firebase_database: ^3.1.0
  image_picker: ^0.6.2+1
  connectivity: ^0.4.5+3
  shared_preferences: ^0.5.4+5
  sqflite: ^1.1.7+3
  dio: ^3.0.6
  flutter_sound: ^1.5.2
  video_player: ^0.10.3+1
  fluttertoast: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/bg_chat.png
    - assets/avatar_1.jpg
    - assets/avatar_2.jpg

